### ISSUE TITLE
regd the link not working

### ISSUE THREAD

**Issue by vpsampath123** [suryakantamangaraj/SmartFarming#1]
Hi Surya,

below link is not working
https://garvana.xyz/
![Capture jpg github](https://github.com/user-attachments/assets/098626b3-fea1-414b-a0ff-2064038ceac2)

thanks and regards,
V.P.Sampath

**Comment by suryakantamangaraj** [comment]
Thank you for bringing this to my attention. Although it was a significant project in the past, I am no longer actively working on it. However, I have provided a new link to keep the dummy site live.
